export const appStrings = {
	config: {
		EMPLOYEE_API_BASE_URL: "http://localhost:8080/employees",
		CREATE_EMPLOYEE_URL: "http://localhost:8080/employees/create",
		UPDATE_EMPLOYEE_URL: "http://localhost:8080/employees/update",
		DELETE_EMPLOYEE_URL: "http://localhost:8080/employees/delete",

		DEPARTMENT_API_BASE_URL: "http://localhost:8080/departments",
		CREATE_DEPARTMENT_URL: "http://localhost:8080/departments/create",
		UPDATE_DEPARTMENT_URL: "http://localhost:8080/departments/update",
		DELETE_DEPARTMENT_URL: "http://localhost:8080/departments/delete",
	},
	notification: {
		departmentUpdateNotificationError: "Input Department Name!!!",
		missingFieldsNotification: "Fill All Input Fields",
	},

	buttonsText: {
		home: "Home",
		addEmployee: "Add Employee",
		addDepartment: "Add Department",
		update: "Update",
		delete: "Delete",
		view: "View",
		explore: "Explore!",
	},
	departmentTableHeader: {
		departmentId: "Deparrtment Id",
		departmentName: "Department Name",
		numOfEmployees: "Number of Employees",
		actions: "Actions",
	},
	employeeTableHeader: {
		employeeId: "Employee Id",
		fullname: "Full Name",
		emailAddress: "Email Address",
		role: "Role",
		department: "Department",
		actions: "Actions",
	},

	emailSuffix: "@hireling.com",
	updateDepartment: "Update Department",
	createDepartment: "Create Department",
	updateEmployee: "Update Employee",
	createEmployee: "Create Employee",
	departments: "Departments",
	save: "Save",
	cancel: "Cancel",
	employees: "Employees",
	employeeDetails: "Employee Details",
	fullName: "Full Name",
	emailAddress: "Email Address",
	role: "Role",
	department: "Department",
	detailsOfEmployees: "Details of Employee",
	backToEmployees: "Back to Employees List",
	departmentDetails: "Department Details",
	departmentId: "Department Id",
	departmentName: "Department Name",
	costCode: "Cost Code",
	NumOfEmployees: "Number of Employees",
	backToDepartment: "Back to Department List",
	bodyText: "World class people with world class solutions!",
	welcomeText: "Welcome to Hireling",
	selectDepartment: "Select Department",
};
